version: '3.8'

services:
  fastapi:
    image: nullis0/fastapi-app:latest
    build:
      context: .
    container_name: fastapi-app
    ports:
      - 8000:8000

  nginx:
    image: nullis0/nginx-proxy:latest
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx_proxy
    ports:
      - 80:80
    depends_on:
      - fastapi
