version: '3.8'

services:
  fastapi:
    build:
      context: .
    env_file:
      - .env
    container_name: fastapi-app
    ports:
      - 8000:8000
    # networks:
    #   - app_network

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: nginx_proxy
    ports:
      - 80:80
    depends_on:
      - fastapi
    env_file:
      - .env
    # networks:
    #   - app_network
    # networks:
    #   app_network:
    #     driver: bridge
