version: '3.8'

services:
  fastapi:
    build:
      context: .
    env_file:
      - .env
    container_name: ${SERVER_HOST}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    # networks:
    #   - app_network

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: ${NGINX_HOST}
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - fastapi
    env_file:
      - .env
    # networks:
    #   - app_network
    # networks:
    #   app_network:
    #     driver: bridge
