name: test

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest || exit -1

            docker run -d \
              --name nginx_proxy \
              --network $NETWORK_NAME \
              -p 80:80 \
              ${{ secrets.DOCKER_USERNAME }}/nginx_proxy:latest
