name: book-store

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest
  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Login Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
     # - name: "Build and push Docker images"
      #  uses: docker/build-push-action@v2
        #with:
         # context: .
        #  file: ./Dockerfile
        #  push: true
       #   tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest
      
      #- name: "Build and push nginx image"
        #uses: docker/build-push-action@v2
        #with:
          #context: .
          #file: ./nginx.Dockerfile
          #push: true
          #tags: ${{ secrets.DOCKER_USERNAME }}/nginx_proxy:latest
      - name: Set up Docker Compose
        uses: KengoTODA/actions-setup-docker-compose@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Build and push Docker images with Docker Compose
        run: |
          docker-compose build
          docker-compose push

      - name: Deploy to AWS EC2 using SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}       # The public IP of your EC2 instance
          username: ${{ secrets.EC2_USER }}                      # SSH username (usually ec2-user for Amazon Linux)
          key: ${{ secrets.SSH_PRIVATE_KEY }}   # Your private SSH key
          port: 22                                  # Default SSH port
          script: |
            # Pull the latest Docker images
            docker-compose pull
            
            # Stop and remove any existing containers
            docker-compose down || true

            # Run the updated containers
            docker-compose up -d
