name: "fastapi-book CI"

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: "setup python"
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"
            - name: "install dependencies"
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: "run tests"
              run: |
                  pytest
    deploy:  
            runs-on: ubuntu-latest
            needs: test  
            if: github.ref == 'refs/heads/main'  # Run only when merged to main
            steps:
                - uses: actions/checkout@v2
                - name: "Deploy application"
                  run: |
                    pytest
                    echo "Deploying application"